# Generated by Django 5.0.7 on 2024-07-23 16:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('founder', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='fie',
            fields=[
                ('shareholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.shareholder')),
                ('name', models.CharField(max_length=100)),
                ('registry_code', models.CharField(max_length=7)),
            ],
            bases=('base.shareholder',),
        ),
        migrations.CreateModel(
            name='physical',
            fields=[
                ('shareholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.shareholder')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nic', models.CharField(max_length=12)),
            ],
            bases=('base.shareholder',),
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registry_code', models.CharField(max_length=7)),
                ('proprietor_first_entry_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 7, 23))])),
                ('total_capital', models.IntegerField(validators=[django.core.validators.MinValueValidator(2500)])),
                ('fie', models.BooleanField(default=False)),
                ('shareholder', models.ManyToManyField(to='base.shareholder')),
            ],
        ),
    ]
