# Generated by Django 5.0.7 on 2024-07-30 18:50

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_enterprise_fie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='first_entry_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 7, 30))]),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='registry_code',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='fie',
            name='registry_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='physical',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='physical',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='physical',
            name='nic',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
